song_1 MACRO; Twinkle Star
    beep note_C3, 900
    sleep 200
    beep note_C3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_A3, 900
    sleep 200
    beep note_A3, 900
    sleep 200
    beep note_G3, 900
    sleep 400
    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_D3, 900
    
    sleep 600
    beep note_C3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    
    sleep 600

    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_C3, 900
    sleep 200
    beep note_C3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_A3, 900
    sleep 200

    sleep 600

    beep note_A3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_C3, 900
ENDM

song_2 MACRO; Jingle Bells
    beep note_E3, 500
    sleep 100
    beep note_E3, 500
    sleep 100
    beep note_E3, 500
    sleep 100
    sleep 500

    beep note_E3, 500
    sleep 100
    beep note_E3, 500
    sleep 100
    beep note_E3, 500
    sleep 500
    
    beep note_E3, 500
    beep note_G3, 500
    beep note_C3, 500
    beep note_D3, 500
    beep note_E3, 500
    sleep 1000

ENDM