song_1 MACRO; Twinkle Star
    beep note_C3, 900
    sleep 200
    beep note_C3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_A3, 900
    sleep 200
    beep note_A3, 900
    sleep 200
    beep note_G3, 900
    sleep 400
    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_D3, 900
    
    sleep 600
    beep note_C3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    
    sleep 600

    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_C3, 900
    sleep 200
    beep note_C3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_A3, 900
    sleep 200

    sleep 600

    beep note_A3, 900
    sleep 200
    beep note_G3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_F3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_E3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_D3, 900
    sleep 200
    beep note_C3, 900
ENDM

song_2 MACRO; mario bros
    beep note_E4, 100
    sleep 100
    beep note_E4, 100
    sleep 300
    beep note_E4, 100
    sleep 300
    beep note_C4, 100
    sleep 100
    beep note_E4, 100
    sleep 300
    beep note_G4, 100
    sleep 300
    beep note_G3, 100
    sleep 300

    beep note_C4, 100
    sleep 300
    beep note_G3, 100
    sleep 300
    beep note_E3, 100
    sleep 300

    beep note_A3, 100
    sleep 100
    beep note_B3, 100
    sleep 300
    beep note_Asharp3, 100
    beep note_A3, 100
    sleep 300

ENDM