song_1 MACRO 
;mario bros
    beep note_E4,100 
    sleep 100 
    beep note_E4,100 
    sleep 300 
    beep note_E4,100 
    sleep 300 
    beep note_C4,100 
    sleep 100 
    beep note_E4,100 
    sleep 300 
    beep note_G4,100 
    sleep 700 
    beep note_G3,100 
    sleep 700 
    beep note_C4,300 
    sleep 300 
    beep note_G3,300 
    sleep 300 
    beep note_E3,300 
    sleep 300 
    beep note_A3,300 
    sleep 100 
    beep note_B3,100 
    sleep 300 
    beep note_Asharp3,200 
    beep note_A3,100 
    sleep 300 
    beep note_G3,100 
    sleep 150 
    beep note_E4,100 
    sleep 150 
    beep note_G4,100 
    sleep 150 
    beep note_A4,100 
    sleep 300 
    beep note_F4,100 
    sleep 100 
    beep note_G4,100 
    sleep 300 
    beep note_E4,100 
    sleep 300 
    beep note_C4,100 
    sleep 100 
    beep note_D4,100 
    sleep 100 
    beep note_B3,100 
    sleep 500 
    beep note_C4,300 
    sleep 300 
    beep note_G3,300 
    sleep 300 
    beep note_E3,300 
    sleep 300 
    beep note_A3,300 
    sleep 100 
    beep note_B3,100 
    sleep 300 
    beep note_Asharp3,200 
    beep note_A3,100 
    sleep 300 
    beep note_G3,100 
    sleep 150 
    beep note_E4,100 
    sleep 150 
    beep note_G4,100 
    sleep 150 
    beep note_A4,100 
    sleep 300 
    beep note_F4,100 
    sleep 100 
    beep note_G4,100 
    sleep 300 
    beep note_E4,100 
    sleep 300 
    beep note_C4,100 
    sleep 100 
    beep note_D4,100 
    sleep 100 
    beep note_B3,100 
    sleep 900 
    beep note_G4,100 
    sleep 100 
    beep note_Fsharp4,100 
    sleep 100 
    beep note_F4,100 
    sleep 100 
    beep note_Dsharp4,100 
    sleep 300 
    beep note_E4,100 
    sleep 300 
    beep note_Gsharp3,100 
    sleep 100 
    beep note_A3,100 
    sleep 100 
    beep note_C4,100 
    sleep 300 
    beep note_A3,100 
    sleep 100 
    beep note_C4,100 
    sleep 100 
    beep note_D4,100 
    sleep 500 
    beep note_G4,100 
    sleep 100 
    beep note_Fsharp4,100 
    sleep 100 
    beep note_F4,100 
    sleep 100 
    beep note_Dsharp4,100 
    sleep 300 
    beep note_E4,100 
    sleep 300 
    beep note_C5,100 
    sleep 300 
    beep note_C5,100 
    sleep 100 
    beep note_C5,100 
    sleep 1100 
    beep note_G4,100 
    sleep 100 
    beep note_Fsharp4,100 
    sleep 100 
    beep note_F4,100 
    sleep 100 
    beep note_Dsharp4,100 
    sleep 300 
    beep note_E4,100 
    sleep 300 
    beep note_Gsharp3,100 
    sleep 100 
    beep note_A3,100 
    sleep 100 
    beep note_C4,100 
    sleep 300 
    beep note_A3,100 
    sleep 100 
    beep note_C4,100 
    sleep 100 
    beep note_D4,100 
    sleep 500 
    beep note_Dsharp4,300 
    sleep 300 
    beep note_D4,300 
    sleep 300 
    beep note_C4,300 
    sleep 1300 
    beep note_C4,100 
    sleep 100 
    beep note_C4,100 
    sleep 300 
    beep note_C4,100 
    sleep 300 
    beep note_C4,100 
    sleep 100 
    beep note_D4,100 
    sleep 300 
    beep note_E4,200 
    sleep 50 
    beep note_C4,200 
    sleep 50 
    beep note_A3,200 
    sleep 50 
    beep note_G3,100 
    sleep 700 
ENDM

song_2 MACRO
;Zelda song Of Time
    beep note_A4, 750 
    beep note_D4, 1500 
    beep note_F4, 750 

    beep note_A4, 750 
    beep note_D4, 1500 
    beep note_F4, 750 

    beep note_A4, 375 
    beep note_C5, 375 
    beep note_B4, 750 
    beep note_G4, 750 
    beep note_F4, 375 
    beep note_G4, 375 

    beep note_A4, 750 
    beep note_D4, 750 
    beep note_C4, 375 
    beep note_E4, 375 
    beep note_D4, 2750 


    beep note_A4, 750 
    beep note_D4, 1500 
    beep note_F4, 750 

    beep note_A4, 750 
    beep note_D4, 1500 
    beep note_F4, 750 

    beep note_A4, 375 
    beep note_C5, 375 
    beep note_B4, 750 
    beep note_G4, 750 
    beep note_F4, 375 
    beep note_G4, 375 

    beep note_A4, 750 
    beep note_D4, 750 
    beep note_C4, 375 
    beep note_E4, 375 
    beep note_D4, 2750 


    beep note_D4, 375 
    beep note_C4, 375 
    beep note_E4, 750 
    beep note_C4, 750 
    beep note_E4, 375 
    beep note_F4, 375 

    beep note_D4, 2000 

ENDM

song_3 MACRO 
;Fur Elise
    beep note_A3, 350
    beep note_Dsharp4, 350
    beep note_E4, 350
    beep note_Dsharp4, 350
    beep note_E4, 350
    beep note_B3, 350
    sleep 50
    beep note_D4, 350
    sleep 50
    beep note_C4, 350
    sleep 50
    beep note_A3, 900
    sleep 750
    beep note_D3, 350
    beep note_F3, 350
    sleep 50
    beep note_A3, 350
    sleep 50
    beep note_B3, 900
    sleep 750
    beep note_F3, 350
    sleep 50
    beep note_Asharp3, 350
    sleep 50
    beep note_B3, 350
    sleep 50
    beep note_C4, 900
    sleep 750
    sleep 750
    beep note_E4, 350
    sleep 50
    beep note_Dsharp4, 350
    beep note_E4, 350
    sleep 50
    beep note_Dsharp4, 350
    sleep 50
    beep note_E4, 350
    sleep 50
    beep note_B3, 350
    sleep 50
    beep note_D4, 350
    sleep 50
    beep note_C4, 350
    sleep 50
    beep note_A3, 900
    sleep 750
    beep note_D3, 350
    sleep 50
    beep note_F3, 350
    sleep 50
    beep note_A3, 350
    sleep 50
    beep note_B3, 900
    sleep 750
    beep note_F3, 350
    sleep 50
    beep note_C4, 350
    sleep 50
    beep note_B3, 350
    sleep 50
    beep note_A3, 900
    sleep 750
    beep note_B3, 350
    sleep 50
    beep note_C4, 350
    sleep 50
    beep note_D4, 350
    sleep 50
    beep note_E4, 900
    sleep 750
    beep note_G3, 350
    sleep 50
    beep note_F4, 350
    sleep 50
    beep note_E4, 350
    sleep 50
    beep note_D4, 900
    sleep 750
    beep note_E3, 350
    sleep 50
    beep note_E4, 350
    sleep 50
    beep note_D4, 350
    sleep 50
    beep note_C4, 900
    sleep 750
    beep note_D3, 350
    sleep 50
    beep note_D4, 350
    sleep 50
    beep note_C4, 350
    sleep 50
    beep note_B3, 900
    sleep 750
    sleep 50
    beep note_E4, 350
    sleep 50
    beep note_Dsharp4, 350
    sleep 50
    beep note_E4, 350
    sleep 50
    beep note_Dsharp4, 350
ENDM

song_4 MACRO
;Despacito
    beep note_D5,709 
    sleep 788 
    sleep 10 
    beep note_Csharp5,709 
    sleep 788 

    beep note_B4,273 
    sleep 304 

    beep note_Fsharp4,273 
    sleep 304 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_B4,134 
    sleep 149 

    beep note_B4,134 
    sleep 149 

    beep note_B4,134 
    sleep 149 

    beep note_B4,273 
    sleep 304 

    beep note_A4,134 
    sleep 149 

    beep note_B4,273 
    sleep 304 

    beep note_G4,412 
    sleep 458 

    beep note_G4,134 
    sleep 149 

    beep note_G4,134 
    sleep 149 

    beep note_G4,134 
    sleep 149 

    beep note_G4,134 
    sleep 149 

    beep note_G4,134 
    sleep 149 

    beep note_B4,134 
    sleep 149 

    beep note_B4,134 
    sleep 149 

    beep note_B4,134 
    sleep 149 

    beep note_B4,273 
    sleep 304 

    beep note_Csharp5,134 
    sleep 149 

    beep note_D5,273 
    sleep 304 

    beep note_A4,412 
    sleep 458 

    beep note_A4,134 
    sleep 149 

    beep note_A4,134 
    sleep 149 

    beep note_A4,134 
    sleep 149 

    beep note_A4,417 
    sleep 46 
    sleep 36 
    beep note_A4,37 
    sleep 41 
    sleep 30 
    beep note_A4,134 
    sleep 149 

    beep note_D5,134 
    sleep 149 

    beep note_D5,134 
    sleep 149 

    beep note_D5,46 
    sleep 51 
    sleep 30 
    beep note_D5,46 
    sleep 51 
    sleep 20 
    beep note_D5,273 
    sleep 304 

    beep note_E5,134 
    sleep 149 

    beep note_E5,273 
    sleep 304 

    beep note_Csharp5,691 
    sleep 767 
    sleep 314 
    beep note_D5,552 
    sleep 613 

    beep note_Csharp5,552 
    sleep 613 

    beep note_B4,273 
    sleep 304 

    beep note_Fsharp4,273 
    sleep 304 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_Fsharp4,134 
    sleep 149 

    beep note_B4,46 
    sleep 51 
    sleep 30 
    beep note_B4,46 
    sleep 304 

    beep note_Csharp5,134 
    sleep 149 

    beep note_D5,273 
    sleep 304 

    beep note_A4,412 
    sleep 458 

    beep note_A4,134 
    sleep 149 

    beep note_A4,64 
    sleep 72 

    beep note_A4,64 
    sleep 72 

    beep note_A4,134 
    sleep 149 

    beep note_A4,134 
    sleep 149 

    beep note_A4,134 
    sleep 149 

    beep note_D5,134 
    sleep 149 

    beep note_D5,134 
    sleep 155
    beep note_D5,51 
    sleep 56 
    beep note_D5,51 
ENDM